
services:
  backend:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile.dev
    container_name: text-analyzer-backend-dev
    environment:
      NODE_ENV: development
      DATABASE_HOST: postgres
      REDIS_HOST: redis
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test:
        ["CMD-SHELL", "curl -f http://localhost:3000/api/v1/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  postgres:
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - ./docker/database/init.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./docker/database/seed.sql:/docker-entrypoint-initdb.d/02-seed.sql

  redis:
    volumes:
      - redis_data_dev:/data

volumes:
  postgres_data_dev:
    driver: local
  redis_data_dev:
    driver: local
