version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile.prod
    container_name: text-analyzer-backend-prod
    environment:
      NODE_ENV: production
      DATABASE_HOST: postgres
      REDIS_HOST: redis
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: always
    healthcheck:
      test:
        ["CMD-SHELL", "curl -f http://localhost:3000/api/v1/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1G
        reservations:
          cpus: "0.5"
          memory: 512M

  postgres:
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
      - ./docker/database/init.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./docker/database/seed.sql:/docker-entrypoint-initdb.d/02-seed.sql
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M

  redis:
    volumes:
      - redis_data_prod:/data
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 256M

volumes:
  postgres_data_prod:
    driver: local
  redis_data_prod:
    driver: local
